AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create S3 bucket and IAM role

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vita66

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: 's3:*'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Principal:
              AWS: '*'
    
  UploadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3UploadRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3UploadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
