name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name my-s3-stack

      - name: Export SQL data
        run: |
          # Add your script here to export SQL data to a file
          # For example, use pg_dump for PostgreSQL or mysqldump for MySQL
          echo "Exporting SQL data"

      - name: Upload data to S3
        run: |
          aws s3 cp C:\Users\DELL\Downloads\rawdata.csv s3://vita66/
