name: Deploy AWS Glue Crawler and Catalog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name glue-crawler-catalog-stack \
            --template-file cloudformation/crawler-template.yml \
            --capabilities CAPABILITY_IAM
